name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Naprise are you running?
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: What .NET version and operating system are you running on?
      placeholder: .NET 6 on Windows 10 and Ubuntu 20.04
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What is happening.
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Info
      description: Add any other context about the problem here.
