name: Feature Request
description: Suggest an idea
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Info
      description: Add any other context about the feature request here.
