site_name: Naprise
site_url: https://genteure.github.io/naprise
repo_url: https://github.com/Genteure/naprise
repo_name: Genteure/naprise
edit_uri: blob/main/docs/
site_description: A .NET library for sending notifications to various services
site_author: Genteure
copyright: Copyright © 2022 Genteure

strict: !ENV [CI, false]

nav:
  - index.md
  - service-url.md
  - usage-examples.md
  - new-service.md
  - Services:
    - services/index.md
    - services/apprise.md
    - services/bark.md
    - services/discord.md
    - services/gotify.md
    - services/mailkitemail.md
    - services/notica.md
    - services/notifyrun.md
    - services/ntfy.md
    - services/onebot11.md
    - services/onebot12.md
    - services/pushdeer.md
    - services/pushplus.md
    - services/serverchan.md
    - services/telegram.md

theme:
  language: en
  name: material
  icon:
    repo: fontawesome/brands/github    
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.suggest
    - toc.follow

plugins:
  - minify:
      minify_html: true
  - search:
      lang: en
  - macros:
      on_error_fail: !ENV [CI, false]
      include_dir: include
      include_yaml:
        - services: data/services.json
        - email_platforms: data/email_platforms.json

watch:
  - data
  - include

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

