name: Build & Publish

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7'

    - name: Build, Test, Pack, Publish
      shell: bash
      run: |
        dotnet tool install -g dotnet-releaser
        dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" src/dotnet-releaser.toml

    - name: Upload build artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: src/artifacts-dotnet-releaser
