name: Update copyright year(s) in license file

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1 1 *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          transform: (?<=copyright\s+(?:\(c\)|©)?\s*)(?<from>\d{4})(?:-\d{4})?
          path: |
            LICENSE
            src/Directory.Build.props
            docs/mkdocs.yml
